### ISSUE TITLE
Endpoint to Create User

### ISSUE THREAD

**Issue by nathantspencer** [AtLAS-WVU/AtLAS-server#1]
Response should be a JSON body:

```
{
    "success": false,
    "uniqueUser": true,
    "uniqueEmail": false
    "debug": "debug message"
}
```

**Comment by owiegand** [comment]
finished code for this. Code is the php page: CreateAccount.php.

PHP code accepts the following POST parameters: 
username, password, email, first_name, last_name

Returns the following: 
`{
    "success": false,
    "uniqueUser": true,
    "uniqueEmail": false
    "debug": "debug message"
}`
