### ISSUE TITLE
Endpoint for Sign In/Out

### ISSUE THREAD

**Issue by nathantspencer** [AtLAS-WVU/AtLAS-server#2]
Sign In JSON response body:

```
{
    "success": true,
    "key": "2asd30ga9ajk3219han"
    "debug": "Debug message here"

}
```

Sign Out JSON response body:

```
{
    "success": true
    "debug": "Debug message here"
}
```

**Comment by owiegand** [comment]
The code to authenticate a user on sign has been completed as of 1a9a57a4d88c6c63ecfe1d46f981cb98dd267e29 The code to log out the user is also completed in 0f99edc6c6c4e7be843de73eaf846f8284ac9337
